name: CI

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Get cached composer packages
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          dev: no
          php_version: 7.4
          version: 2

      - name: Run tests
        uses: php-actions/phpunit@v2
        with:
          configuration: phpunit.prod.xml
          php_version: 7.4
          version: 9.5.2
